### ISSUE TITLE
handle POJO bean property timestamp(Long)

### ISSUE THREAD

**Issue by heyunxia** [eBay/xcelite#1]
I have one bean to serialize like this

<div class="highlight" style="background: #272822"><pre style="line-height: 125%">import com.ebay.xcelite.annotations.Column;
import com.ebay.xcelite.annotations.Row;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * @author heyunxia (love3400wind@163.com)
 * @version 1.0
 * @since 2015-10-21 下午12:31
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Row(colsOrder = {&quot;编号&quot;, &quot;姓名&quot;, &quot;支付方式&quot;, &quot;价格&quot;, &quot;支付状态&quot;, &quot;支付时间&quot;})
public class WashOrder implements Serializable {

    private static final long serialVersionUID = 8794087388514650389L;

    /**
     * 主键ID
     */
    @Column(name = &quot;编号&quot;)
    private String id;
    /**
     * 会员姓名
     */
    @Column(name = &quot;姓名&quot;)
    private String name;
    /**
     * 原价
     */
    @Column(name = &quot;价格&quot;, converter = PriceValueConverter.class)
    private Integer sellPrice;

    /**
     * 支付方式
     */
    @Column(name = &quot;支付方式&quot;, converter = EnumValueConverter.class)
    private String payType;

    /**
     * 支付状态
     */
    @Column(name = &quot;支付状态&quot;)
    private Integer payStatus;

    /**
     * 支付时间
     */
    @Column(name = &quot;支付时间&quot;, converter = DateValueConverter.class)
    private Long payAt;
}
</pre></div>

then run my code

<div class="highlight" style="background: #272822"><pre style="line-height: 125%">import com.ebay.xcelite.Xcelite;
import com.ebay.xcelite.sheet.XceliteSheet;
import com.ebay.xcelite.writer.SheetWriter;
import com.google.common.collect.Lists;

import java.io.File;
import java.util.List;

/**
 * @author heyunxia
 * @version 1.0
 * @since 2015-10-21 上午11:39
 */
public class TestExportOrder {
    public static void main(String[] args) {
        Xcelite xcelite = new Xcelite();
        XceliteSheet sheet = xcelite.createSheet(&quot;users&quot;);
        SheetWriter<span style="color: #f92672">&lt;WashOrder&gt;</span> writer = sheet.getBeanWriter(WashOrder.class);
        List<span style="color: #f92672">&lt;WashOrder&gt;</span> users = Lists.newArrayList();
        WashOrder washOrder = new WashOrder(&quot;01&quot;, &quot;姓名&quot;, 1111, &quot;11&quot;, 1, 1444910884496l);
        users.add(washOrder);

        washOrder = new WashOrder(&quot;02&quot;, &quot;姓名1&quot;,111, &quot;12&quot;, 2, 1444900884496l);
        users.add(washOrder);

        washOrder = new WashOrder(&quot;03&quot;, &quot;姓名2&quot;, 111, &quot;14&quot;, 3, 1444911884496l);
        users.add(washOrder);

        washOrder = new WashOrder(&quot;04&quot;, &quot;姓名3&quot;, 1911, &quot;13&quot;, 4, 1444930884496l);
        users.add(washOrder);

        washOrder = new WashOrder(&quot;05&quot;, &quot;姓名4&quot;, 1811, &quot;17&quot;, 5, 1444940884496l);
        users.add(washOrder);

        washOrder = new WashOrder(&quot;06&quot;, &quot;姓名5&quot;, 1981, &quot;19&quot;, 7, 1444910584496l);
        users.add(washOrder);

        writer.write(users);
        xcelite.write(new File(&quot;users_doc.xlsx&quot;));

    }
}
</pre></div>

I got this

<div class="highlight" style="background: #272822"><pre style="line-height: 125%">Exception in thread &quot;main&quot; java.lang.RuntimeException: java.lang.NumberFormatException: For input string: &quot;2015-10-15 20:08:04&quot;
    at com.ebay.xcelite.writer.BeanSheetWriter.writeData(BeanSheetWriter.java:94)
    at com.ebay.xcelite.writer.BeanSheetWriter.write(BeanSheetWriter.java:58)
    at TestExportOrder.main(TestExportOrder.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NumberFormatException: For input string: &quot;2015-10-15 20:08:04&quot;
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.valueOf(Double.java:504)
    at com.ebay.xcelite.writer.SheetWriterAbs.writeToCell(SheetWriterAbs.java:54)
    at com.ebay.xcelite.writer.BeanSheetWriter.writeToCell(BeanSheetWriter.java:127)
    at com.ebay.xcelite.writer.BeanSheetWriter.writeData(BeanSheetWriter.java:86)
    ... 7 more
</pre></div>

after adding the payAt @Column annoatation property ignoreType = true, the error message was missing.

I know ignore=true has worked.

**Comment by heyunxia** [comment]
adding the payAt @Column annoatation property ignoreType = true
